name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.12.0'
    - name: Setup Git Config
      run: |
        git config --global user.email "ci@getfluency.io"
        git config --global user.name "Automated Deployment"
    - name: Report node version
      run: node --version
    - name: Report node location
      run: which node
    - name: Report npm location
      run: which npm
    - name: Report npm version
      run: npm --version
    - name: Clean node modules
      run: rm -rf node_modules
    - name: Clean gatsby cache
      run: rm -rf .cache
    - name: Clean npm cache
      run: npm cache clean --force
    - name: npm install
      run: npm install --verbose
    - name: npm rebuild
      run: npm rebuild
    - name: npm run gatsby-build
      run: npm run gatsby-build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: public
        CNAME: getfluency.io
